### ISSUE TITLE
Set-up production version of application on public URL

### ISSUE THREAD

**Issue by vvorski** [Vorski-Imagineering/share#117]
open application on public URL

**Comment by vvorski** [comment]
I need to buy URL first of course!

**Comment by vvorski** [comment]
created http://share-app.vorski.com/ let's install there.

**Comment by vvorski** [comment]
@rafallo  access info e-mailed

**Comment by vvorski** [comment]
see also #167

**Comment by rafallo** [comment]
@vvorski, what do you want to run under new domain? Whole application or only login page?

I think that we need do following things in order to run Share on non-Parse.com server:
- copy cloudCode/public/ directory into public web directory, which may be served by http server,
- copy generated manifest.js file to public web directory,
- set redirect in some web language (e.g. PHP) from every /sharedItem/{id} url to /#/sharedItem/{id} url (note hash at the beginning).

It SHOULD work, but I'm concerned about cross-domain POST restriction.

**Comment by vvorski** [comment]
@rafallo ok, please set it up on share-app.vorski.com, login info sent via e-mail.

**Comment by rafallo** [comment]
it works

**Comment by vvorski** [comment]
shared-app.vorski.com works, now need to set-up http://shared.gift/ but that's another ticket I think.
